"""add ticker column to stock_prices

Revision ID: b7065e5b92da
Revises: d1f736b76a4e
Create Date: 2026-03-08 12:15:26.596760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7065e5b92da'
down_revision: Union[str, Sequence[str], None] = 'd1f736b76a4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('stock_prices_stock_id_fkey', 'stock_prices', type_='foreignkey')
    op.drop_column('stock_prices', 'stock_id')
    op.drop_table('stocks')
    op.add_column('stock_prices', sa.Column('ticker', sa.String(length=10), nullable=True))
    op.alter_column('stock_prices', 'date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('stock_prices', 'open',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=4),
               existing_nullable=True)
    op.alter_column('stock_prices', 'close',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=4),
               existing_nullable=True)
    op.alter_column('stock_prices', 'high',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=4),
               existing_nullable=True)
    op.alter_column('stock_prices', 'low',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=4),
               existing_nullable=True)
    op.alter_column('stock_prices', 'volume',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.BigInteger(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_prices', sa.Column('stock_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('stock_prices_stock_id_fkey'), 'stock_prices', 'stocks', ['stock_id'], ['id'])
    op.alter_column('stock_prices', 'volume',
               existing_type=sa.BigInteger(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('stock_prices', 'low',
               existing_type=sa.Numeric(precision=12, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('stock_prices', 'high',
               existing_type=sa.Numeric(precision=12, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('stock_prices', 'close',
               existing_type=sa.Numeric(precision=12, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('stock_prices', 'open',
               existing_type=sa.Numeric(precision=12, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('stock_prices', 'date',
               existing_type=sa.DATE(),
               nullable=False)
    op.drop_column('stock_prices', 'ticker')
    op.create_table('stocks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('sector', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('stocks_pkey')),
    sa.UniqueConstraint('ticker', name=op.f('stocks_ticker_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
